name: 01-buildingblocks
on: push

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: say hello
              run: echo "hello!"
    echo-bye:
        runs-on: ubuntu-latest
        steps:
            - name: successful
              run: |
                echo "I will be a success"
                exit 0
            - name: bye
              run: echo "byee"
